ApexWorkbook/src/objects/Bug__c.object
<CustomObject>
    <description>For QA Bugs</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Logged_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Logged By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bugs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>1 - Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 - High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Bug</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhancement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bug</label>
    <nameField>
        <displayFormat>BUG-{0000}</displayFormat>
        <label>Bug Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ApexWorkbook/src/classes/BugCreator.cls
Global class BugCreator implements Messaging.inboundEmailHandler {
    Global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope env) {
    
        Messaging.InboundEmailResult result = new Messaging.InboundEmailResult();
        createBug(email.subject, email.plainTextBody, env.fromAddress);
        result.success = true;
        return result;
    
    }
    
    public static Bug__c createBug(String BugDescr, String BugBody, String fromEmail) {
        List<User> finduser = [SELECT Id FROM User WHERE Email = :fromEmail];
        User founduser;
        if (finduser.size() > 0) {
            founduser = finduser[0];
        } else {
            List<User> randomuser = [SELECT Id FROM User];
            founduser = randomuser[0];
        }
    
        Bug__c newBug = new Bug__c(Title__c = BugDescr, Description__c = BugBody, Status__c = 'New', Type__c = 'Bug', Priority__c = '2 - High', Logged_By__c = foundUser.Id);
        insert newBug;
        return newBug;
    
    }
    
    


}