ApexWorkbook/src/objects/SalesOrder__x.object
<CustomObject>
    <description>SalesOrder</description>
    <externalDataSource>SAP_OData_Demo</externalDataSource>
    <externalName>SalesOrder</externalName>
    <fields>
        <fullName>businessPartnerId__c</fullName>
        <description>businessPartnerId</description>
        <externalDeveloperName>businessPartnerId</externalDeveloperName>
        <label>businessPartnerId</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>currency__c</fullName>
        <description>currency</description>
        <externalDeveloperName>currency</externalDeveloperName>
        <label>currency</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>netSum__c</fullName>
        <description>netSum</description>
        <externalDeveloperName>netSum</externalDeveloperName>
        <label>netSum</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>note__c</fullName>
        <description>note</description>
        <externalDeveloperName>note</externalDeveloperName>
        <label>note</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>totalSum__c</fullName>
        <description>totalSum</description>
        <externalDeveloperName>totalSum</externalDeveloperName>
        <label>totalSum</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>SalesOrder</label>
    <pluralLabel>SalesOrder</pluralLabel>
</CustomObject>

ApexWorkbook/src/classes/SapOrdersAccountControllerExtension.cls
public class SapOrdersAccountControllerExtension {
    private final Account acct;
    List<SalesOrder__x> orderList;
    
    public sapOrdersAccountControllerExtension(ApexPages.StandardController stdController) {
        Account a = (Account)stdController.getRecord();
        List<Account> res = [SELECT Id, AccountNumber FROM Account WHERE Id = :a.Id LIMIT 1];
        this.acct = res.get(0);
    }
    
    public String getSapCustomerId() {
        return acct.AccountNumber;
    }
    
    public List<SalesOrder__x> getOrderList() {
        if (null == this.orderList) {
            orderList = [SELECT ExternalId, Note__c, Currency__c, NetSum__c, TotalSum__c FROM SalesOrder__x WHERE BusinessPartnerID__c = :this.acct.AccountNumber];
        }
        return orderList;
    }
}